/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample19_A */

#ifndef _Included_sample19_A
#define _Included_sample19_A
#ifdef __cplusplus
extern "C" {
#endif
#undef sample19_A_serialVersionUID
#define sample19_A_serialVersionUID 20201202095200LL
/*
 * Class:     sample19_A
 * Method:    fn2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample19_A_fn2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
